/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanteenCreateDialog: typeof import('./components/CanteenCreateDialog.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    DishFormDialog: typeof import('./components/DishFormDialog.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    EntityImage: typeof import('./components/EntityImage.vue')['default']
    FilterBar: typeof import('./components/layout/FilterBar.vue')['default']
    FilterSelect: typeof import('./components/layout/FilterSelect.vue')['default']
    FormDialog: typeof import('./components/FormDialog.vue')['default']
    ImageUpload: typeof import('./components/ImageUpload.vue')['default']
    InlineSelectPanel: typeof import('./components/InlineSelectPanel.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    PageContainer: typeof import('./components/layout/PageContainer.vue')['default']
    PageHeader: typeof import('./components/layout/PageHeader.vue')['default']
    PageSection: typeof import('./components/layout/PageSection.vue')['default']
    RenameEntityDialog: typeof import('./components/RenameEntityDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StallCreateDialog: typeof import('./components/StallCreateDialog.vue')['default']
    StarRating: typeof import('./components/StarRating.vue')['default']
    StatCard: typeof import('./components/common/StatCard.vue')['default']
    StatusTag: typeof import('./components/StatusTag.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    UserActivityModal: typeof import('./components/UserActivityModal.vue')['default']
  }
}
