/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseDrawer: typeof import('./components/BaseDrawer.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    ImageUpload: typeof import('./components/ImageUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateBox: typeof import('./components/StateBox.vue')['default']
    StatusTag: typeof import('./components/StatusTag.vue')['default']
  }
}
